project_style:
  content_structure:  simple_image
  should_register:    false
  get_druid_from:     container
  use_druid_minter:   false

bundle_dir:           spec/test_data/bundle_input_b
staging_dir:          tmp

manifest:             ~
checksums_file:       ~
desc_md_template:     ~

progress_log_file:    log/progress_rumsey.yaml
project_name:         Rumsey
apo_druid_id:         ~
set_druid_id:         ~

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     false

content_md_creation:
  style:              :default
  pre_md_file:        ~

object_discovery:
  use_manifest:       false
  glob:               '*'
  regex:              '^[a-z][a-z]\d\d\d[a-z][a-z]\d\d\d\d$'

stageable_discovery:
  use_container:      false
  glob:               '*'
  regex:              '(?ix) ^ ( \d+\.tif | descMetadata\.xml ) $'

manifest_cols:
  object_container:   ~
  source_id:          ~
  label:              ~

content_exclusion:    '(?ix) descMetadata\.xml $'

validate_usage:       true
show_progress:        true
limit_n:              10
uniqify_source_ids:   true
cleanup:              true
