# This is an example from the Gould project.  Objects have been pre-registered, are contained in folders identifying druids, with content to be staged in '00' subfolders.

project_style:
  content_structure: 'simple_book'
  get_druid_from: 'container'

bundle_dir:  '/thumpers/dpgthumper-staging/Gould'
staging_dir: ~
accession_items:   ~

object_discovery:
 use_manifest: false
 glob:  '*'
 regex: '^[a-z][a-z]\d\d\d[a-z][a-z]\d\d\d\d$'

stageable_discovery:
  use_container: false
  glob:  '00/*'
  regex: ~

manifest:   ~
checksums_file:   ~
desc_md_template: ~

manifest_cols:
  object_container:   ~
  source_id:          ~
  label:              ~

project_name:      'Gould'

progress_log_file: '/dor/preassembly/gould_log.yaml'
apo_druid_id: ~
set_druid_id: ~

content_exclusion: ~

content_md_creation:
  style:       'default'

publish_attr: ~
