project_style:
  content_structure:  'simple_image'
  should_register:    true
  get_druid_from:     'suri'
  use_druid_minter:   false

bundle_dir:           '/home/lyberadmin/pre-assembly/revs_test_run/input'
staging_dir:          '/dor/assembly'

manifest:             'manifest.csv'
checksums_file:       'checksums.txt'
desc_md_template:     'mods_template.xml'

progress_log_file:    'log/progress_revs.yaml'
project_name:         'Revs'
apo_druid_id:         'druid:qv648vd4392'
set_druid_id:         'druid:yt502zj0924'

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     true

content_md_creation:
  style:              :default
  pre_md_file:        ~

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   'filename'
  source_id:          'sourceid'
  label:              'label'

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              10
uniqify_source_ids:   false
cleanup:              false
